### PR TITLE
LPS-74530 Display auto in both cases, zero and blank.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-adaptive-media/pull/54. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-adaptive-media/pull/55. [See changes here.](https://github.com/4lejandrito/com-liferay-adaptive-media/compare/0ce7e78~1...0ce7e78) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
